[build]
  command = "npm run build"
  publish = "dist/krh-auto/browser"

[dev]
  command = "ng serve -c dev"
  targetPort = 4200
  port = 8888
  framework = "angular"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"