[build]
  command = "npm run build"
  publish = "dist/krh-auto/browser"

[dev]
  command = "npm start"
  port = 4200
  targetPort = 4200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"